// Fetching and freeing the .glb files the runner is made of.
//
// Everything borrowed out of CS2 by src/playerModelPipeline.js is handled the same way:
// fetched once, cloned per instance, freed when the last instance is gone. Both sides of
// that belong together, and in one place, because the two have to agree about what an
// instance owns and what it only points at.

import { GLTFLoader } from "three/addons/loaders/GLTFLoader.js";
import { MeshoptDecoder } from "three/addons/libs/meshopt_decoder.module.js";

/**
 * Fetch one .glb, resolving to null rather than throwing when it is not there.
 *
 * A missing file is a normal state, not an error: everything loaded through here is
 * generated by `npm run player-model` and, like a converted map, is not in the repository.
 * A checkout that has not run it still plays every replay — player.js keeps its white ball
 * and the runner is empty-handed.
 */
export const loadGlb = (url) =>
  new Promise((resolve) => {
    const loader = new GLTFLoader().setMeshoptDecoder(MeshoptDecoder);
    loader.load(
      url,
      (gltf) => resolve(gltf),
      undefined,
      () => resolve(null),
    );
  });

/**
 * Free a loaded asset's geometry and textures.
 *
 * The shared half of the job, and the last step: an instance's own cloned materials are
 * its to free, but the geometry and the textures are what every clone pointed at, so this
 * runs only once nothing is left pointing at them.
 */
export const disposeGlb = (asset) => {
  asset?.scene?.traverse((child) => {
    if (!child.isMesh) return;
    child.geometry.dispose();
    for (const material of [child.material].flat()) {
      for (const value of Object.values(material)) {
        if (value?.isTexture) value.dispose();
      }
      material.dispose();
    }
  });
};
